---
title: "AQI_cleaning"
author: "Brecken Enright"
date: "2024-09-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages
```{r}
library(tidyverse)
```

Read in data
```{r}
full_AQI_data <- read_csv("us-epa-pm25-aqi-updated.csv")
head(full_AQI_data)
```


```{r}
filtered_full_AQI <- full_AQI_data |> select(DateTime, `HMC Jacobs 4 A`, 
                                             `HMC Jacobs 4 B` )
head(filtered_full_AQI)
```


```{r}
startDate = as.POSIXct("2024-09-05 00:10:00")
endDate = as.POSIXct("2024-09-15 00:10:00")

recent_AQI_data <- filtered_full_AQI |>
  filter(DateTime > startDate)

recent_AQI_data_2 <- recent_AQI_data |>
  filter(DateTime < endDate)


head(recent_AQI_data_2)

```

Add average of both sensor chanels
```{r}
recent_AQI_data_final <- recent_AQI_data_2 |>
  mutate(sensor_4_average = ((`HMC Jacobs 4 A` + `HMC Jacobs 4 B`)/2)) 
```

Find Worst AQI During Period analyzed
```{r}
J4A_max = max(recent_AQI_data_final$`HMC Jacobs 4 A`)
J4B_max = max(recent_AQI_data_final$`HMC Jacobs 4 B`)

J4A_max
J4B_max

date_4A_max <- recent_AQI_data_final %>%
  filter(`HMC Jacobs 4 A` == J4A_max)

date_4A_max
```

```{r}
recent_AQI_data_final <- recent_AQI_data_final %>% rename(
  date = DateTime,
  PA_sensor_176379A = `HMC Jacobs 4 A`,
  PA_sensor_176379B = `HMC Jacobs 4 B`,
  avg_PM2.5_AQI = sensor_4_average)

head(recent_AQI_data_final)
```
```{r}
write_csv(recent_AQI_data_final, "us-epa-pm25-aqi-jacobs4-recent-clean.csv")
```

